export const MEMBERS_LIST_REQUEST = "MEMBERS_LIST_REQUEST";
export const MEMBERS_LIST_SUCCESS = "MEMBERS_LIST_SUCCESS";
export const MEMBERS_LIST_FAIL = "MEMBERS_LIST_FAIL";

export const MEMBERS_CREATE_REQUEST = "MEMBERS_CREATE_REQUEST";
export const MEMBERS_CREATE_SUCCESS = "MEMBERS_CREATE_SUCCESS";
export const MEMBERS_CREATE_FAIL = "MEMBERS_CREATE_FAIL";

export const MEMBERS_UPDATE_REQUEST = "MEMBERS_UPDATE_REQUEST";
export const MEMBERS_UPDATE_SUCCESS = "MEMBERS_UPDATE_SUCCESS";
export const MEMBERS_UPDATE_FAIL = "MEMBERS_UPDATE_FAIL";

export const MEMBERS_DELETE_REQUEST = "MEMBERS_DELETE_REQUEST";
export const MEMBERS_DELETE_SUCCESS = "MEMBERS_DELETE_SUCCESS";
export const MEMBERS_DELETE_FAIL = "MEMBERS_DELETE_FAIL";