export const MEMBERS_GALLERY_LIST_REQUEST = "MEMBERS_GALLERY_LIST_REQUEST";
export const MEMBERS_GALLERY_LIST_SUCCESS = "MEMBERS_GALLERY_LIST_SUCCESS";
export const MEMBERS_GALLERY_LIST_FAIL = "MEMBERS_GALLERY_LIST_FAIL";

export const MEMBERS_GALLERY_CREATE_REQUEST = "MEMBERS_GALLERY_CREATE_REQUEST";
export const MEMBERS_GALLERY_CREATE_SUCCESS = "MEMBERS_GALLERY_CREATE_SUCCESS";
export const MEMBERS_GALLERY_CREATE_FAIL = "MEMBERS_GALLERY_CREATE_FAIL";

export const MEMBERS_GALLERY_DELETE_REQUEST = "MEMBERS_GALLERY_DELETE_REQUEST";
export const MEMBERS_GALLERY_DELETE_SUCCESS = "MEMBERS_GALLERY_DELETE_SUCCESS";
export const MEMBERS_GALLERY_DELETE_FAIL = "MEMBERS_GALLERY_DELETE_FAIL";